### ISSUE TITLE
Niceties should not close

### ISSUE THREAD

**Issue by mjec** [mjec/rc-niceties#12]
> People should be able to contribute at any point in their batch, and at the end of their batch they should also be reminded to share kinds words with people of the next batch (since both batches would have known each other for 6 weeks, sharing shouldn't be just one way).

See [this issue on the rc issue tracker](https://github.com/recursecenter/issue-tracker/issues/101)

**Comment by jasonaowen** [comment]
I just discussed this with @christalee, and implementation-wise, I think this means removing the concept of niceties closing throughout the app: deleting the utility method `niceties_are_open`, the call site in API, the `{ "status": "closed" }` response, the front-end check for that response, and the "Niceties are closed!" message itself.
