### ISSUE TITLE
Put warning up until niceties is fixed

### ISSUE THREAD

**Issue by jasonaowen** [mjec/rc-niceties#21]
Until the issues that are preventing staff from using niceties.recurse.com are resolved, it would be useful to have a disclaimer on the site warning users to only submit niceties via the most recent Google form.

Suggested by @rhonorv on [RC Zulip :lock:](https://recurse.zulipchat.com/#narrow/stream/19042-397-Bridge/topic/Niceties.3F.3F.3F/near/172773838).

**Comment by christalee** [comment]
Hi! I stumbled upon niceties.recurse.com and I'm interested in perhaps reviving it, or at least starting with this pull request. I have the site built and running locally. (Thanks for whoever wrote the excellent instructions!) 

Did you have something more sophisticated in mind than just adding some text to index.html? I'm new to React so if there's something to be done there I might need a pointer.

**Comment by jasonaowen** [comment]
> I stumbled upon niceties.recurse.com and I'm interested in perhaps reviving it, or at least starting with this pull request.

That's wonderful to hear! I haven't had much time to do development work on this, but I'd love to support you in reviving it.

> Did you have something more sophisticated in mind than just adding some text to index.html? I'm new to React so if there's something to be done there I might need a pointer.

That sounds like a great approach! The goal is just to avoid niceties getting lost because they're getting submitted to the wrong place. There are definitely more complicated implementations we could think about, but that time and effort would probably be better spent on fixing the underlying issues, so yes, adding some text to the HTML sounds perfect. :)

**Comment by jasonaowen** [comment]
Done in #26. Thanks, @christalee!
