### ISSUE TITLE
placeholder text for encouraging people to write niceties

### ISSUE THREAD

**Issue by xtrntr** [mjec/rc-niceties#4]
Here are sources of information to pull from:
- their github repos. There's a cap on the amount of API calls that can be made, so results are cached. The necessary github API calls are commented out for now.
- their bio/skills/during-rc/before-rc key values, but people don't always fill them out.
- Zulip data. This might get a little intrusive, so @horacepan suggested only mentioning what streams they are most active in. Even then it might be iffy as a source of data.

**Comment by christalee** [comment]
Closed per my previous comment, and commit 7299afee2dc14796e54e9faeaf90b6b2fd9e495d. Please reopen if you have additional requirements.
