### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by jasonaowen** [mjec/rc-niceties#52]
The default branch of this repo used the default-at-the-time name of `master`. That name has some problematic associations, and its only upside is inertia; in particular, I don't believe the name is in keeping with the "No Subtle -isms" [RC Social Rule](https://www.recurse.com/manual#sub-sec-social-rules).

The convention that the community seems to be settling on as a new name for the default branch is `main`. [GitHub now uses `main` for the default branch on new repositories](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name), and [Heroku supports deployments via git pushes to either `master` or `main`](https://devcenter.heroku.com/articles/git-branches).

Please rename the default branch from `master` to `main`. I believe this is something only @mjec can do, but [GitHub has made it easy to do so](https://github.com/github/renaming#rename-existing).

See also:
- [Software Freedom Conservancy statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)

**Comment by mjec** [comment]
Thanks for calling this out @jasonaowen. I'll rename the branch to `main` later this evening, around 8pm NY time (cc @christalee in case this impacts your workflow).

**Comment by mjec** [comment]
Branch renamed `main`, let me know if you run into trouble!

**Comment by jasonaowen** [comment]
Thank you, @mjec!

:heart:
:octopus: 

GitHub even gave me a helpful notice when I looked at your repo:

![Screen Shot 2021-04-17 at 18 50 23](https://user-images.githubusercontent.com/1494855/115098401-c46ad580-9ee4-11eb-81c3-47eb5497d571.png)

**Comment by jasonaowen** [comment]
I had to click the "Enable automatic deploys" button in Heroku, as it apparently turned itself off when the `master` branch was deleted. Sorry about that, I don't remember having that problem with https://github.com/jasonaowen/recurse-faces/issues/78 ! Looks like the next merge should be automatically deployed again.

![Heroku deployment configuration](https://user-images.githubusercontent.com/1494855/115128803-4adef000-9f95-11eb-91ff-db2181b1b3da.png)
